import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Modal from "./components/modals/Modal";
import LoginModal from "./components/modals/LoginModal";
import SignUpModal from "./components/modals/SignUpModal";
import AddPropertyModal from "./components/modals/AddPropertyModal";
import SearchModal from "./components/modals/SearchModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Django-AirBnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const content = (<p>asdfsd</p>)
  

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        <div className="pt-32">
          {children}
        </div>

        <LoginModal/>
        <SignUpModal/>
        <AddPropertyModal/>
        <SearchModal/>
        {/* <Modal label="Modal text"
        content={content}
        isOpen={false}/> */}
        </body>
    </html>
  );
}
